---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator(orchestrator)
	display_papers(display_papers)
	ask_upload(ask_upload)
	ask_single_file(ask_single_file)
	extract_formatted(extract_formatted)
	summarise_paper(summarise_paper)
	summary_critic(summary_critic)
	return_with_caveat(return_with_caveat)
	finalize_summary(finalize_summary)
	set_papers(set_papers)
	check_pdf_input_node(check_pdf_input_node)
	ask_compare_upload(ask_compare_upload)
	check_compatibility(check_compatibility)
	compare_papers(compare_papers)
	summarize_comparison(summarize_comparison)
	validate_and_query(validate_and_query)
	compare_router_node(compare_router_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> orchestrator;
	ask_single_file --> check_pdf_input_node;
	ask_upload --> check_pdf_input_node;
	check_compatibility -. &nbsp;incompatible&nbsp; .-> __end__;
	check_compatibility -. &nbsp;compare&nbsp; .-> compare_papers;
	check_pdf_input_node -.-> ask_single_file;
	check_pdf_input_node -.-> ask_upload;
	check_pdf_input_node -. &nbsp;process_file&nbsp; .-> extract_formatted;
	compare_papers --> summarize_comparison;
	compare_router_node -. &nbsp;ask_upload&nbsp; .-> ask_compare_upload;
	compare_router_node -. &nbsp;uploaded&nbsp; .-> check_compatibility;
	extract_formatted --> summarise_paper;
	orchestrator -. &nbsp;summarize&nbsp; .-> check_pdf_input_node;
	orchestrator -. &nbsp;compare&nbsp; .-> compare_router_node;
	orchestrator -. &nbsp;discover&nbsp; .-> set_papers;
	set_papers -. &nbsp;compare&nbsp; .-> check_compatibility;
	set_papers -. &nbsp;discover&nbsp; .-> display_papers;
	set_papers -. &nbsp;validate&nbsp; .-> validate_and_query;
	summarise_paper --> summary_critic;
	summary_critic -. &nbsp;pass&nbsp; .-> finalize_summary;
	summary_critic -. &nbsp;max_reached&nbsp; .-> return_with_caveat;
	summary_critic -. &nbsp;retry&nbsp; .-> summarise_paper;
	ask_compare_upload --> __end__;
	display_papers --> __end__;
	finalize_summary --> __end__;
	return_with_caveat --> __end__;
	summarize_comparison --> __end__;
	validate_and_query --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
